### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by daquinoaldo** [znpm/zargparse#3]
Write more test cases to extend the coverage.

Please work on the branch `test`.
Run `npm t` to run tests and see the coverage.

**Comment by Rhuancpq** [comment]
I can try this

**Comment by MarcoBomfim** [comment]
@daquinoaldo, may I help on this one?

**Comment by daquinoaldo** [comment]
@MarcoBomfim any news? Are you still interested?

**Comment by MarcoBomfim** [comment]
@daquinoaldo, sorry, got caught up this week. I'm still interested though. Will work on it throughout the week

**Comment by daquinoaldo** [comment]
No problem

**Comment by MarcoBomfim** [comment]
@daquinoaldo seems like I don't have permission to commit to the `test` branch. Do you have any recommended steps to open the PR?

**Comment by daquinoaldo** [comment]
Seems you have not forked the repository.
Here is [how to fork a repository](https://help.github.com/en/articles/fork-a-repo#fork-an-example-repository) and here you can find [how to open a pull request](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork).

Let me know if you have some difficulties in opening the PR, I'll be glad to help you!

**Comment by MarcoBomfim** [comment]
You're 100% right, don't know what I was thinking. Anyway, just opened the PR.

**Comment by daquinoaldo** [comment]
Merged. Thank you very much for contributing 🍻
